Add RenderBytes function and method
narqo/go-badge pull request #11
Opened 2019-01-23 06:06 UTC by montanaflynn

As requested in #4

2019-01-23 11:27 UTC, narqo requested changes
Oh, wow, thank's for peeking this up. The change looks ok, but I think we can improve it a bit.

2019-01-23 11:27 UTC, narqo commented on badge.go
> +func (d *badgeDrawer) RenderBytes(subject, status string, color Color) ([]byte, error) {
How do you feel about making it a wrapper around `(*badgeDrawer).Render()`, instead of duplicating it's logic? 

As `bytes.Buffer` implements `io.Writer`, it should be easier to do it like below:

```go
func (d) RenderBytes(···) ([]byte, error) {
  var buf bytes.Buffer
  err := d.Render(···, &buf)
  return buf.Bytes(), err
}
```

2019-01-24 03:15 UTC, montanaflynn commented on badge.go
> +func (d *badgeDrawer) RenderBytes(subject, status string, color Color) ([]byte, error) {
Great idea!

2019-01-24 11:03 UTC, narqo approved these changes

2019-01-24 11:03 UTC, merged